
services:
  mongo:
    image: mongo:6.0
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - moustass-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - '3001:3001'
    depends_on:
      - mongo
    networks:
      - moustass-net

  frontend:
    build:
      context: ./frontend       
      dockerfile: Dockerfile 
      args:
       - REACT_APP_API_URL=http://backend:3001
    environment:
      - REACT_APP_API_URL=http://backend:3001   
    ports:
      - '3000:80'
    depends_on:
      - backend
    networks:
      - moustass-net

volumes:
  mongo-data:

networks:
  moustass-net:
    driver: bridge
