
services:
  mongo:
    image: mongo:6.0
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - moustass-net

  api:            
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    networks:
      - moustass-net

  ui:            
    build:
      context: ./frontend       
      dockerfile: Dockerfile 
      args:
       - REACT_APP_API_URL=http://api:3001
    environment:
      - REACT_APP_API_URL=http://api:3001   
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - moustass-net
  
  proxy:
    build: 
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/logs:/usr/local/apache2/logs
    depends_on:
      - api
      - ui
    networks:
      - moustass-net

volumes:
  mongo-data:

networks:
  moustass-net:
    driver: bridge
